from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from time import perf_counter
from typing import Any

from common.schemas import make_ai_message, validate_ai_message
from common.path_utils import resolve_from_file

from .complexity import latest_user_text
from .deep_think_tot import DeepThinkToT
from .plan_executor import PlanExecutor
from .prompt_builder import _build_prompt_messages
from .qwen_client import qwen_generate_completion
from .router import ROUTE_DEEP_THINK, ROUTE_DIRECT_ANSWER, ROUTE_PLAN_EXECUTE, ROUTE_TOOL_CALL, RouteDecision

_MODEL_CACHE: dict[tuple[str, ...], tuple[Any, Any]] = {}

_NO_MORE_CONTENT = "\u5de5\u5177\u7ed3\u679c\u672a\u63d0\u4f9b\u66f4\u591a\u53ef\u63d0\u53d6\u5185\u5bb9"
_THREE_POINTS_PREFIX = "\u4e09\u6761\u4e2d\u6587\u8981\u70b9\u5982\u4e0b\uff1a\n"
_TOOL_FAILED_PREFIX = "\u5de5\u5177\u8c03\u7528\u5931\u8d25\uff0c\u65e0\u6cd5\u5b8c\u6210\u8bf7\u6c42\uff1a"
_UNKNOWN_TOOL_ERROR = "\u672a\u77e5\u5de5\u5177\u9519\u8bef"
_DIRECT_ANSWER = "This is a direct answer generated by the B4 mock router."
_DEEP_THINK_ANSWER = "Analysis: the request needs reasoning, so B4 selected the deep_think route."


class MockAdapter:
    """Deterministic mock backend used for tests and no-model runs."""

    def invoke(
        self,
        messages: list[dict[str, Any]],
        tools_schema: list[dict[str, Any]],
        config_path: Path,
        config: dict[str, Any],
        route_decision: RouteDecision | None = None,
        fixture: dict[str, Any] | None = None,
        goal_analysis: dict[str, Any] | None = None,
        reflection: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        started = perf_counter()
        if fixture is not None or route_decision is not None:
            ai_message = _mock_router_generate(messages, tools_schema, fixture, route_decision, goal_analysis, reflection)
        else:
            ai_message = _mock_generate(messages)
        return {
            "raw_text": _message_to_raw_text(ai_message),
            "backend": "mock",
            "model": "mock",
            "usage": None,
            "latency_ms": round((perf_counter() - started) * 1000, 3),
        }


class TransformersPromptJsonAdapter:
    """Local transformers backend that asks the model for one JSON object."""

    def invoke(
        self,
        messages: list[dict[str, Any]],
        tools_schema: list[dict[str, Any]],
        config_path: Path,
        config: dict[str, Any],
        route_decision: RouteDecision | None = None,
        fixture: dict[str, Any] | None = None,
        goal_analysis: dict[str, Any] | None = None,
        reflection: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        started = perf_counter()
        completion = _prompt_json_generate(config_path, config, messages, tools_schema)
        model_config = config.get("model", {}) if isinstance(config.get("model"), dict) else {}
        return {
            "raw_text": completion["text"],
            "backend": model_config.get("backend", "transformers"),
            "model": model_config.get("model_name_or_path"),
            "usage": completion.get("usage"),
            "latency_ms": round((perf_counter() - started) * 1000, 3),
        }


def get_adapter(mode: str) -> MockAdapter | TransformersPromptJsonAdapter:
    if mode == "mock":
        return MockAdapter()
    if mode == "prompt_json":
        return TransformersPromptJsonAdapter()
    raise ValueError("mode must be mock or prompt_json")


def _extract_tool_result(message: dict[str, Any]) -> dict[str, Any]:
    try:
        result = json.loads(message["content"])
    except (KeyError, json.JSONDecodeError, TypeError) as exc:
        raise ValueError("ToolMessage content is not a SkillResult JSON string") from exc
    if not isinstance(result, dict):
        raise ValueError("ToolMessage content must decode to an object")
    return result


def _three_points(text: str) -> list[str]:
    parts = [part.strip(" \t\r\n\u3002") for part in re.split(r"\n+|(?<=[\u3002\uff01\uff1f!?])", text) if part.strip()]
    points: list[str] = []
    for part in parts:
        if part not in points:
            points.append(part)
        if len(points) == 3:
            break
    while len(points) < 3:
        points.append(_NO_MORE_CONTENT)
    return points


def _mock_generate(messages: list[dict[str, Any]]) -> dict[str, Any]:
    tool_messages = [message for message in messages if message.get("role") == "tool"]
    if not tool_messages:
        return make_ai_message(
            "",
            [
                {
                    "id": "call_001",
                    "name": "file_reader",
                    "args": {"path": "docs/agent_intro.txt", "max_chars": 2000},
                }
            ],
        )
    latest = tool_messages[-1]
    result = _extract_tool_result(latest)
    if latest.get("status") != "success" or result.get("status") != "success":
        error = result.get("error") or {}
        detail = error.get("message", _UNKNOWN_TOOL_ERROR) if isinstance(error, dict) else str(error)
        return make_ai_message(f"{_TOOL_FAILED_PREFIX}{detail}", [])
    output = result.get("output") or {}
    content = output.get("content") if isinstance(output, dict) else None
    if not isinstance(content, str) or not content.strip():
        content = json.dumps(output, ensure_ascii=False)
    points = _three_points(content)
    answer = _THREE_POINTS_PREFIX + "\n".join(f"{index}. {point}" for index, point in enumerate(points, 1))
    return make_ai_message(answer, [])


def _mock_router_generate(
    messages: list[dict[str, Any]],
    tools_schema: list[dict[str, Any]],
    fixture: dict[str, Any] | None = None,
    route_decision: RouteDecision | None = None,
    goal_analysis: dict[str, Any] | None = None,
    reflection: dict[str, Any] | None = None,
) -> dict[str, Any]:
    if fixture is not None:
        return _message_from_fixture(fixture, messages, tools_schema, route_decision, goal_analysis, reflection)
    if route_decision is None:
        return _mock_generate(messages)
    metadata = route_decision.to_dict()
    if goal_analysis is not None:
        metadata.setdefault("goal_analysis", goal_analysis)
    if reflection is not None:
        metadata.setdefault("reflection", reflection)
    if route_decision.route == ROUTE_DIRECT_ANSWER:
        if messages and messages[-1].get("role") == "tool":
            message = _mock_generate(messages)
        else:
            message = make_ai_message(_DIRECT_ANSWER, [])
    elif route_decision.route == ROUTE_DEEP_THINK:
        tot_result = DeepThinkToT().run(latest_user_text(messages), _latest_tool_context(messages))
        metadata.setdefault("deep_think_tot", tot_result.to_dict())
        message = make_ai_message(tot_result.to_process_text(), [])
    elif route_decision.route == ROUTE_TOOL_CALL:
        message = _mock_generate(messages)
    elif route_decision.route == ROUTE_PLAN_EXECUTE:
        plan = PlanExecutor().create_plan(messages, tools_schema, goal_analysis=goal_analysis)
        message = PlanExecutor().plan_to_ai_message(plan, metadata)
    else:
        message = _mock_generate(messages)
    message.setdefault("metadata", {}).update(metadata)
    validate_ai_message(message)
    return message


def _latest_tool_context(messages: list[dict[str, Any]]) -> str | None:
    latest_tool = next((message for message in reversed(messages) if message.get("role") == "tool"), None)
    if latest_tool is None or not isinstance(latest_tool.get("content"), str):
        return None
    content = latest_tool["content"]
    try:
        payload = json.loads(content)
    except json.JSONDecodeError:
        return content
    output = payload.get("output") if isinstance(payload, dict) else None
    if isinstance(output, dict) and isinstance(output.get("content"), str):
        return output["content"]
    return content


def _message_from_fixture(
    fixture: dict[str, Any],
    messages: list[dict[str, Any]],
    tools_schema: list[dict[str, Any]],
    route_decision: RouteDecision | None,
    goal_analysis: dict[str, Any] | None = None,
    reflection: dict[str, Any] | None = None,
) -> dict[str, Any]:
    route = fixture.get("route")
    response = fixture.get("response", {})
    if not isinstance(response, dict):
        raise ValueError("B4 router fixture response must be an object")
    content = response.get("content", "")
    if not content and route == ROUTE_DEEP_THINK and isinstance(fixture.get("think_content"), str):
        content = fixture["think_content"]
    message: dict[str, Any] = {
        "role": "assistant",
        "content": content,
        "tool_calls": response.get("tool_calls", []),
    }
    metadata = route_decision.to_dict() if route_decision else {}
    if goal_analysis is not None:
        metadata.setdefault("goal_analysis", goal_analysis)
    if reflection is not None:
        metadata.setdefault("reflection", reflection)
    if route:
        metadata.setdefault("route", route)
    if fixture.get("complexity"):
        metadata.setdefault("complexity", fixture["complexity"])
    if metadata:
        message["metadata"] = metadata
    if route == ROUTE_PLAN_EXECUTE:
        plan = PlanExecutor().create_plan(messages, tools_schema, goal_analysis=goal_analysis, fixture=fixture)
        if not message["content"] and not message["tool_calls"]:
            return PlanExecutor().plan_to_ai_message(plan, metadata)
        message["type"] = ROUTE_PLAN_EXECUTE
        message["plan"] = plan
    validate_ai_message(message)
    return message


def _message_to_raw_text(message: dict[str, Any]) -> str:
    payload = {"content": message.get("content", ""), "tool_calls": message.get("tool_calls", [])}
    for key in ("type", "plan", "metadata"):
        if key in message:
            payload[key] = message[key]
    return json.dumps(payload, ensure_ascii=False)


def _dtype_value(torch_module: Any, configured: str) -> Any:
    if configured == "auto":
        return "auto"
    mapping = {
        "bfloat16": torch_module.bfloat16,
        "float16": torch_module.float16,
        "float32": torch_module.float32,
    }
    if configured not in mapping:
        raise ValueError(f"unsupported torch_dtype: {configured}")
    return mapping[configured]


def _model_cache_key(
    model_path: Path,
    tokenizer_path: Path,
    local_only: bool,
    trust_remote_code: bool,
    dtype: Any,
    device_map: Any,
    max_memory: Any,
) -> tuple[str, ...]:
    try:
        device_map_key = json.dumps(device_map, sort_keys=True, separators=(",", ":"))
    except TypeError:
        device_map_key = repr(device_map)
    try:
        max_memory_key = json.dumps(max_memory, sort_keys=True, separators=(",", ":"))
    except TypeError:
        max_memory_key = repr(max_memory)
    return (
        str(model_path),
        str(tokenizer_path),
        str(local_only),
        str(trust_remote_code),
        str(dtype),
        device_map_key,
        max_memory_key,
    )


def _load_model_bundle(
    auto_model: Any,
    auto_tokenizer: Any,
    model_path: Path,
    tokenizer_path: Path,
    local_only: bool,
    trust_remote_code: bool,
    dtype: Any,
    device_map: Any,
    max_memory: Any,
) -> tuple[Any, Any]:
    cache_key = _model_cache_key(
        model_path,
        tokenizer_path,
        local_only,
        trust_remote_code,
        dtype,
        device_map,
        max_memory,
    )
    cached = _MODEL_CACHE.get(cache_key)
    if cached is not None:
        print("model_cache=hit", file=sys.stderr, flush=True)
        return cached

    print("model_cache=miss", file=sys.stderr, flush=True)
    tokenizer = auto_tokenizer.from_pretrained(
        str(tokenizer_path),
        local_files_only=local_only,
        trust_remote_code=trust_remote_code,
    )
    model = auto_model.from_pretrained(
        str(model_path),
        local_files_only=local_only,
        trust_remote_code=trust_remote_code,
        dtype=dtype,
        device_map=device_map,
        max_memory=max_memory,
    )
    _MODEL_CACHE[cache_key] = (tokenizer, model)
    return tokenizer, model


def _prompt_json_generate(
    config_path: Path,
    config: dict[str, Any],
    messages: list[dict[str, Any]],
    tools_schema: list[dict[str, Any]],
) -> dict[str, Any]:
    tool_calling = config.get("tool_calling", {}) if isinstance(config.get("tool_calling"), dict) else {}
    schema_mode = tool_calling.get("mode", "prompt_json")
    prompt_tools_schema = [] if schema_mode == "builtin_tools" else tools_schema
    prompt_messages = _build_prompt_messages(messages, prompt_tools_schema)
    return qwen_generate_completion(
        config_path,
        config,
        prompt_messages,
        tools_schema=tools_schema if schema_mode == "builtin_tools" else None,
    )
